export interface Card {
  set: string;
  id: string;
  name: string;
  rarity: string;
}

export const getCardImageUrl = (card: Pick<Card, "set" | "id">) => {
  return `https://limitlesstcg.nyc3.cdn.digitaloceanspaces.com/pocket/${card.set}/${card.set}_${card.id}_EN.webp`;
};

export const doRaritiesMatch = (
  a: Pick<Card, "set" | "id">,
  b: Pick<Card, "set" | "id">
) => {
  return (
    CARDS.find((c) => c.set === a.set && c.id === a.id)?.rarity ===
    CARDS.find((c) => c.set === b.set && c.id === b.id)?.rarity
  );
};

export const findCard = (info: Pick<Card, "set" | "id">) => {
  return CARDS.find((c) => c.set === info.set && c.id === info.id);
};

export const CARDS: Card[] = [
  { set: "A1", id: "001", name: "Bulbasaur", rarity: "◊" },
  { set: "A1", id: "002", name: "Ivysaur", rarity: "◊◊" },
  { set: "A1", id: "003", name: "Venusaur", rarity: "◊◊◊" },
  { set: "A1", id: "004", name: "Venusaur ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "005", name: "Caterpie", rarity: "◊" },
  { set: "A1", id: "006", name: "Metapod", rarity: "◊" },
  { set: "A1", id: "007", name: "Butterfree", rarity: "◊◊◊" },
  { set: "A1", id: "008", name: "Weedle", rarity: "◊" },
  { set: "A1", id: "009", name: "Kakuna", rarity: "◊" },
  { set: "A1", id: "010", name: "Beedrill", rarity: "◊◊◊" },
  { set: "A1", id: "011", name: "Oddish", rarity: "◊" },
  { set: "A1", id: "012", name: "Gloom", rarity: "◊◊" },
  { set: "A1", id: "013", name: "Vileplume", rarity: "◊◊◊" },
  { set: "A1", id: "014", name: "Paras", rarity: "◊" },
  { set: "A1", id: "015", name: "Parasect", rarity: "◊◊" },
  { set: "A1", id: "016", name: "Venonat", rarity: "◊" },
  { set: "A1", id: "017", name: "Venomoth", rarity: "◊◊" },
  { set: "A1", id: "018", name: "Bellsprout", rarity: "◊" },
  { set: "A1", id: "019", name: "Weepinbell", rarity: "◊◊" },
  { set: "A1", id: "020", name: "Victreebel", rarity: "◊◊◊" },
  { set: "A1", id: "021", name: "Exeggcute", rarity: "◊" },
  { set: "A1", id: "022", name: "Exeggutor", rarity: "◊◊◊" },
  { set: "A1", id: "023", name: "Exeggutor ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "024", name: "Tangela", rarity: "◊" },
  { set: "A1", id: "025", name: "Scyther", rarity: "◊" },
  { set: "A1", id: "026", name: "Pinsir", rarity: "◊◊" },
  { set: "A1", id: "027", name: "Cottonee", rarity: "◊" },
  { set: "A1", id: "028", name: "Whimsicott", rarity: "◊◊" },
  { set: "A1", id: "029", name: "Petilil", rarity: "◊" },
  { set: "A1", id: "030", name: "Lilligant", rarity: "◊◊" },
  { set: "A1", id: "031", name: "Skiddo", rarity: "◊" },
  { set: "A1", id: "032", name: "Gogoat", rarity: "◊" },
  { set: "A1", id: "033", name: "Charmander", rarity: "◊" },
  { set: "A1", id: "034", name: "Charmeleon", rarity: "◊◊" },
  { set: "A1", id: "035", name: "Charizard", rarity: "◊◊◊" },
  { set: "A1", id: "036", name: "Charizard ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "037", name: "Vulpix", rarity: "◊" },
  { set: "A1", id: "038", name: "Ninetales", rarity: "◊◊" },
  { set: "A1", id: "039", name: "Growlithe", rarity: "◊" },
  { set: "A1", id: "040", name: "Arcanine", rarity: "◊◊◊" },
  { set: "A1", id: "041", name: "Arcanine ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "042", name: "Ponyta", rarity: "◊" },
  { set: "A1", id: "043", name: "Rapidash", rarity: "◊◊" },
  { set: "A1", id: "044", name: "Magmar", rarity: "◊" },
  { set: "A1", id: "045", name: "Flareon", rarity: "◊◊◊" },
  { set: "A1", id: "046", name: "Moltres", rarity: "◊◊◊" },
  { set: "A1", id: "047", name: "Moltres ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "048", name: "Heatmor", rarity: "◊" },
  { set: "A1", id: "049", name: "Salandit", rarity: "◊" },
  { set: "A1", id: "050", name: "Salazzle", rarity: "◊" },
  { set: "A1", id: "051", name: "Sizzlipede", rarity: "◊" },
  { set: "A1", id: "052", name: "Centiskorch", rarity: "◊◊" },
  { set: "A1", id: "053", name: "Squirtle", rarity: "◊" },
  { set: "A1", id: "054", name: "Wartortle", rarity: "◊◊" },
  { set: "A1", id: "055", name: "Blastoise", rarity: "◊◊◊" },
  { set: "A1", id: "056", name: "Blastoise ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "057", name: "Psyduck", rarity: "◊" },
  { set: "A1", id: "058", name: "Golduck", rarity: "◊◊" },
  { set: "A1", id: "059", name: "Poliwag", rarity: "◊" },
  { set: "A1", id: "060", name: "Poliwhirl", rarity: "◊◊" },
  { set: "A1", id: "061", name: "Poliwrath", rarity: "◊◊◊" },
  { set: "A1", id: "062", name: "Tentacool", rarity: "◊" },
  { set: "A1", id: "063", name: "Tentacruel", rarity: "◊◊" },
  { set: "A1", id: "064", name: "Seel", rarity: "◊" },
  { set: "A1", id: "065", name: "Dewgong", rarity: "◊◊" },
  { set: "A1", id: "066", name: "Shellder", rarity: "◊" },
  { set: "A1", id: "067", name: "Cloyster", rarity: "◊◊" },
  { set: "A1", id: "068", name: "Krabby", rarity: "◊" },
  { set: "A1", id: "069", name: "Kingler", rarity: "◊◊" },
  { set: "A1", id: "070", name: "Horsea", rarity: "◊" },
  { set: "A1", id: "071", name: "Seadra", rarity: "◊◊" },
  { set: "A1", id: "072", name: "Goldeen", rarity: "◊" },
  { set: "A1", id: "073", name: "Seaking", rarity: "◊" },
  { set: "A1", id: "074", name: "Staryu", rarity: "◊" },
  { set: "A1", id: "075", name: "Starmie", rarity: "◊◊" },
  { set: "A1", id: "076", name: "Starmie ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "077", name: "Magikarp", rarity: "◊" },
  { set: "A1", id: "078", name: "Gyarados", rarity: "◊◊◊" },
  { set: "A1", id: "079", name: "Lapras", rarity: "◊◊◊" },
  { set: "A1", id: "080", name: "Vaporeon", rarity: "◊◊◊" },
  { set: "A1", id: "081", name: "Omanyte", rarity: "◊◊" },
  { set: "A1", id: "082", name: "Omastar", rarity: "◊◊◊" },
  { set: "A1", id: "083", name: "Articuno", rarity: "◊◊◊" },
  { set: "A1", id: "084", name: "Articuno ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "085", name: "Ducklett", rarity: "◊" },
  { set: "A1", id: "086", name: "Swanna", rarity: "◊◊" },
  { set: "A1", id: "087", name: "Froakie", rarity: "◊" },
  { set: "A1", id: "088", name: "Frogadier", rarity: "◊◊" },
  { set: "A1", id: "089", name: "Greninja", rarity: "◊◊◊" },
  { set: "A1", id: "090", name: "Pyukumuku", rarity: "◊" },
  { set: "A1", id: "091", name: "Bruxish", rarity: "◊◊" },
  { set: "A1", id: "092", name: "Snom", rarity: "◊" },
  { set: "A1", id: "093", name: "Frosmoth", rarity: "◊◊" },
  { set: "A1", id: "094", name: "Pikachu", rarity: "◊" },
  { set: "A1", id: "095", name: "Raichu", rarity: "◊◊◊" },
  { set: "A1", id: "096", name: "Pikachu ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "097", name: "Magnemite", rarity: "◊" },
  { set: "A1", id: "098", name: "Magneton", rarity: "◊◊◊" },
  { set: "A1", id: "099", name: "Voltorb", rarity: "◊" },
  { set: "A1", id: "100", name: "Electrode", rarity: "◊◊" },
  { set: "A1", id: "101", name: "Electabuzz", rarity: "◊" },
  { set: "A1", id: "102", name: "Jolteon", rarity: "◊◊◊" },
  { set: "A1", id: "103", name: "Zapdos", rarity: "◊◊◊" },
  { set: "A1", id: "104", name: "Zapdos ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "105", name: "Blitzle", rarity: "◊" },
  { set: "A1", id: "106", name: "Zebstrika", rarity: "◊◊" },
  { set: "A1", id: "107", name: "Tynamo", rarity: "◊" },
  { set: "A1", id: "108", name: "Eelektrik", rarity: "◊◊" },
  { set: "A1", id: "109", name: "Eelektross", rarity: "◊◊◊" },
  { set: "A1", id: "110", name: "Helioptile", rarity: "◊" },
  { set: "A1", id: "111", name: "Heliolisk", rarity: "◊" },
  { set: "A1", id: "112", name: "Pincurchin", rarity: "◊◊" },
  { set: "A1", id: "113", name: "Clefairy", rarity: "◊" },
  { set: "A1", id: "114", name: "Clefable", rarity: "◊◊" },
  { set: "A1", id: "115", name: "Abra", rarity: "◊" },
  { set: "A1", id: "116", name: "Kadabra", rarity: "◊◊" },
  { set: "A1", id: "117", name: "Alakazam", rarity: "◊◊◊" },
  { set: "A1", id: "118", name: "Slowpoke", rarity: "◊" },
  { set: "A1", id: "119", name: "Slowbro", rarity: "◊◊" },
  { set: "A1", id: "120", name: "Gastly", rarity: "◊" },
  { set: "A1", id: "121", name: "Haunter", rarity: "◊◊" },
  { set: "A1", id: "122", name: "Gengar", rarity: "◊◊◊" },
  { set: "A1", id: "123", name: "Gengar ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "124", name: "Drowzee", rarity: "◊" },
  { set: "A1", id: "125", name: "Hypno", rarity: "◊◊◊" },
  { set: "A1", id: "126", name: "Mr. Mime", rarity: "◊◊" },
  { set: "A1", id: "127", name: "Jynx", rarity: "◊" },
  { set: "A1", id: "128", name: "Mewtwo", rarity: "◊◊◊" },
  { set: "A1", id: "129", name: "Mewtwo ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "130", name: "Ralts", rarity: "◊" },
  { set: "A1", id: "131", name: "Kirlia", rarity: "◊◊" },
  { set: "A1", id: "132", name: "Gardevoir", rarity: "◊◊◊" },
  { set: "A1", id: "133", name: "Woobat", rarity: "◊" },
  { set: "A1", id: "134", name: "Swoobat", rarity: "◊" },
  { set: "A1", id: "135", name: "Golett", rarity: "◊" },
  { set: "A1", id: "136", name: "Golurk", rarity: "◊◊" },
  { set: "A1", id: "137", name: "Sandshrew", rarity: "◊" },
  { set: "A1", id: "138", name: "Sandslash", rarity: "◊◊" },
  { set: "A1", id: "139", name: "Diglett", rarity: "◊" },
  { set: "A1", id: "140", name: "Dugtrio", rarity: "◊◊" },
  { set: "A1", id: "141", name: "Mankey", rarity: "◊" },
  { set: "A1", id: "142", name: "Primeape", rarity: "◊◊" },
  { set: "A1", id: "143", name: "Machop", rarity: "◊" },
  { set: "A1", id: "144", name: "Machoke", rarity: "◊◊" },
  { set: "A1", id: "145", name: "Machamp", rarity: "◊◊◊" },
  { set: "A1", id: "146", name: "Machamp ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "147", name: "Geodude", rarity: "◊" },
  { set: "A1", id: "148", name: "Graveler", rarity: "◊◊" },
  { set: "A1", id: "149", name: "Golem", rarity: "◊◊◊" },
  { set: "A1", id: "150", name: "Onix", rarity: "◊◊" },
  { set: "A1", id: "151", name: "Cubone", rarity: "◊" },
  { set: "A1", id: "152", name: "Marowak", rarity: "◊◊" },
  { set: "A1", id: "153", name: "Marowak ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "154", name: "Hitmonlee", rarity: "◊" },
  { set: "A1", id: "155", name: "Hitmonchan", rarity: "◊" },
  { set: "A1", id: "156", name: "Rhyhorn", rarity: "◊" },
  { set: "A1", id: "157", name: "Rhydon", rarity: "◊◊" },
  { set: "A1", id: "158", name: "Kabuto", rarity: "◊◊" },
  { set: "A1", id: "159", name: "Kabutops", rarity: "◊◊◊" },
  { set: "A1", id: "160", name: "Mienfoo", rarity: "◊" },
  { set: "A1", id: "161", name: "Mienshao", rarity: "◊◊" },
  { set: "A1", id: "162", name: "Clobbopus", rarity: "◊" },
  { set: "A1", id: "163", name: "Grapploct", rarity: "◊◊" },
  { set: "A1", id: "164", name: "Ekans", rarity: "◊" },
  { set: "A1", id: "165", name: "Arbok", rarity: "◊◊" },
  { set: "A1", id: "166", name: "Nidoran♀", rarity: "◊" },
  { set: "A1", id: "167", name: "Nidorina", rarity: "◊◊" },
  { set: "A1", id: "168", name: "Nidoqueen", rarity: "◊◊◊" },
  { set: "A1", id: "169", name: "Nidoran♂", rarity: "◊" },
  { set: "A1", id: "170", name: "Nidorino", rarity: "◊◊" },
  { set: "A1", id: "171", name: "Nidoking", rarity: "◊◊◊" },
  { set: "A1", id: "172", name: "Zubat", rarity: "◊" },
  { set: "A1", id: "173", name: "Golbat", rarity: "◊◊" },
  { set: "A1", id: "174", name: "Grimer", rarity: "◊" },
  { set: "A1", id: "175", name: "Muk", rarity: "◊◊◊" },
  { set: "A1", id: "176", name: "Koffing", rarity: "◊" },
  { set: "A1", id: "177", name: "Weezing", rarity: "◊◊◊" },
  { set: "A1", id: "178", name: "Mawile", rarity: "◊" },
  { set: "A1", id: "179", name: "Pawniard", rarity: "◊" },
  { set: "A1", id: "180", name: "Bisharp", rarity: "◊◊" },
  { set: "A1", id: "181", name: "Meltan", rarity: "◊" },
  { set: "A1", id: "182", name: "Melmetal", rarity: "◊◊◊" },
  { set: "A1", id: "183", name: "Dratini", rarity: "◊" },
  { set: "A1", id: "184", name: "Dragonair", rarity: "◊◊" },
  { set: "A1", id: "185", name: "Dragonite", rarity: "◊◊◊" },
  { set: "A1", id: "186", name: "Pidgey", rarity: "◊" },
  { set: "A1", id: "187", name: "Pidgeotto", rarity: "◊" },
  { set: "A1", id: "188", name: "Pidgeot", rarity: "◊◊◊" },
  { set: "A1", id: "189", name: "Rattata", rarity: "◊" },
  { set: "A1", id: "190", name: "Raticate", rarity: "◊" },
  { set: "A1", id: "191", name: "Spearow", rarity: "◊" },
  { set: "A1", id: "192", name: "Fearow", rarity: "◊" },
  { set: "A1", id: "193", name: "Jigglypuff", rarity: "◊" },
  { set: "A1", id: "194", name: "Wigglytuff", rarity: "◊" },
  { set: "A1", id: "195", name: "Wigglytuff ex", rarity: "◊◊◊◊" },
  { set: "A1", id: "196", name: "Meowth", rarity: "◊" },
  { set: "A1", id: "197", name: "Persian", rarity: "◊◊" },
  { set: "A1", id: "198", name: "Farfetch'd", rarity: "◊" },
  { set: "A1", id: "199", name: "Doduo", rarity: "◊" },
  { set: "A1", id: "200", name: "Dodrio", rarity: "◊◊" },
  { set: "A1", id: "201", name: "Lickitung", rarity: "◊◊" },
  { set: "A1", id: "202", name: "Chansey", rarity: "◊◊" },
  { set: "A1", id: "203", name: "Kangaskhan", rarity: "◊◊◊" },
  { set: "A1", id: "204", name: "Tauros", rarity: "◊◊" },
  { set: "A1", id: "205", name: "Ditto", rarity: "◊◊◊" },
  { set: "A1", id: "206", name: "Eevee", rarity: "◊" },
  { set: "A1", id: "207", name: "Eevee", rarity: "◊" },
  { set: "A1", id: "208", name: "Eevee", rarity: "◊" },
  { set: "A1", id: "209", name: "Porygon", rarity: "◊◊" },
  { set: "A1", id: "210", name: "Aerodactyl", rarity: "◊◊◊" },
  { set: "A1", id: "211", name: "Snorlax", rarity: "◊◊◊" },
  { set: "A1", id: "212", name: "Minccino", rarity: "◊" },
  { set: "A1", id: "213", name: "Cinccino", rarity: "◊◊" },
  { set: "A1", id: "214", name: "Wooloo", rarity: "◊" },
  { set: "A1", id: "215", name: "Dubwool", rarity: "◊" },
  { set: "A1", id: "216", name: "Helix Fossil", rarity: "◊" },
  { set: "A1", id: "217", name: "Dome Fossil", rarity: "◊" },
  { set: "A1", id: "218", name: "Old Amber", rarity: "◊" },
  { set: "A1", id: "219", name: "Erika", rarity: "◊◊" },
  { set: "A1", id: "220", name: "Misty", rarity: "◊◊" },
  { set: "A1", id: "221", name: "Blaine", rarity: "◊◊" },
  { set: "A1", id: "222", name: "Koga", rarity: "◊◊" },
  { set: "A1", id: "223", name: "Giovanni", rarity: "◊◊" },
  { set: "A1", id: "224", name: "Brock", rarity: "◊◊" },
  { set: "A1", id: "225", name: "Sabrina", rarity: "◊◊" },
  { set: "A1", id: "226", name: "Lt. Surge", rarity: "◊◊" },
  { set: "A1", id: "227", name: "Bulbasaur", rarity: "☆" },
  { set: "A1", id: "228", name: "Gloom", rarity: "☆" },
  { set: "A1", id: "229", name: "Pinsir", rarity: "☆" },
  { set: "A1", id: "230", name: "Charmander", rarity: "☆" },
  { set: "A1", id: "231", name: "Rapidash", rarity: "☆" },
  { set: "A1", id: "232", name: "Squirtle", rarity: "☆" },
  { set: "A1", id: "233", name: "Gyarados", rarity: "☆" },
  { set: "A1", id: "234", name: "Lapras", rarity: "☆" },
  { set: "A1", id: "235", name: "Electrode", rarity: "☆" },
  { set: "A1", id: "236", name: "Alakazam", rarity: "☆" },
  { set: "A1", id: "237", name: "Slowpoke", rarity: "☆" },
  { set: "A1", id: "238", name: "Diglett", rarity: "☆" },
  { set: "A1", id: "239", name: "Cubone", rarity: "☆" },
  { set: "A1", id: "240", name: "Nidoqueen", rarity: "☆" },
  { set: "A1", id: "241", name: "Nidoking", rarity: "☆" },
  { set: "A1", id: "242", name: "Golbat", rarity: "☆" },
  { set: "A1", id: "243", name: "Weezing", rarity: "☆" },
  { set: "A1", id: "244", name: "Dragonite", rarity: "☆" },
  { set: "A1", id: "245", name: "Pidgeot", rarity: "☆" },
  { set: "A1", id: "246", name: "Meowth", rarity: "☆" },
  { set: "A1", id: "247", name: "Ditto", rarity: "☆" },
  { set: "A1", id: "248", name: "Eevee", rarity: "☆" },
  { set: "A1", id: "249", name: "Porygon", rarity: "☆" },
  { set: "A1", id: "250", name: "Snorlax", rarity: "☆" },
  { set: "A1", id: "251", name: "Venusaur ex", rarity: "☆☆" },
  { set: "A1", id: "252", name: "Exeggutor ex", rarity: "☆☆" },
  { set: "A1", id: "253", name: "Charizard ex", rarity: "☆☆" },
  { set: "A1", id: "254", name: "Arcanine ex", rarity: "☆☆" },
  { set: "A1", id: "255", name: "Moltres ex", rarity: "☆☆" },
  { set: "A1", id: "256", name: "Blastoise ex", rarity: "☆☆" },
  { set: "A1", id: "257", name: "Starmie ex", rarity: "☆☆" },
  { set: "A1", id: "258", name: "Articuno ex", rarity: "☆☆" },
  { set: "A1", id: "259", name: "Pikachu ex", rarity: "☆☆" },
  { set: "A1", id: "260", name: "Zapdos ex", rarity: "☆☆" },
  { set: "A1", id: "261", name: "Gengar ex", rarity: "☆☆" },
  { set: "A1", id: "262", name: "Mewtwo ex", rarity: "☆☆" },
  { set: "A1", id: "263", name: "Machamp ex", rarity: "☆☆" },
  { set: "A1", id: "264", name: "Marowak ex", rarity: "☆☆" },
  { set: "A1", id: "265", name: "Wigglytuff ex", rarity: "☆☆" },
  { set: "A1", id: "266", name: "Erika", rarity: "☆☆" },
  { set: "A1", id: "267", name: "Misty", rarity: "☆☆" },
  { set: "A1", id: "268", name: "Blaine", rarity: "☆☆" },
  { set: "A1", id: "269", name: "Koga", rarity: "☆☆" },
  { set: "A1", id: "270", name: "Giovanni", rarity: "☆☆" },
  { set: "A1", id: "271", name: "Brock", rarity: "☆☆" },
  { set: "A1", id: "272", name: "Sabrina", rarity: "☆☆" },
  { set: "A1", id: "273", name: "Lt. Surge", rarity: "☆☆" },
  { set: "A1", id: "274", name: "Moltres ex", rarity: "☆☆" },
  { set: "A1", id: "275", name: "Articuno ex", rarity: "☆☆" },
  { set: "A1", id: "276", name: "Zapdos ex", rarity: "☆☆" },
  { set: "A1", id: "277", name: "Gengar ex", rarity: "☆☆" },
  { set: "A1", id: "278", name: "Machamp ex", rarity: "☆☆" },
  { set: "A1", id: "279", name: "Wigglytuff ex", rarity: "☆☆" },
  { set: "A1", id: "280", name: "Charizard ex", rarity: "☆☆☆" },
  { set: "A1", id: "281", name: "Pikachu ex", rarity: "☆☆☆" },
  { set: "A1", id: "282", name: "Mewtwo ex", rarity: "☆☆☆" },
  { set: "A1", id: "283", name: "Mew", rarity: "☆☆☆" },
  { set: "A1", id: "284", name: "Charizard ex", rarity: "👑" },
  { set: "A1", id: "285", name: "Pikachu ex", rarity: "👑" },
  { set: "A1", id: "286", name: "Mewtwo ex", rarity: "👑" },
  { set: "A1a", id: "001", name: "Exeggcute", rarity: "◊" },
  { set: "A1a", id: "002", name: "Exeggutor", rarity: "◊◊" },
  { set: "A1a", id: "003", name: "Celebi ex", rarity: "◊◊◊◊" },
  { set: "A1a", id: "004", name: "Snivy", rarity: "◊" },
  { set: "A1a", id: "005", name: "Servine", rarity: "◊◊" },
  { set: "A1a", id: "006", name: "Serperior", rarity: "◊◊◊" },
  { set: "A1a", id: "007", name: "Morelull", rarity: "◊" },
  { set: "A1a", id: "008", name: "Shiinotic", rarity: "◊◊" },
  { set: "A1a", id: "009", name: "Dhelmise", rarity: "◊◊" },
  { set: "A1a", id: "010", name: "Ponyta", rarity: "◊" },
  { set: "A1a", id: "011", name: "Rapidash", rarity: "◊◊" },
  { set: "A1a", id: "012", name: "Magmar", rarity: "◊◊" },
  { set: "A1a", id: "013", name: "Larvesta", rarity: "◊" },
  { set: "A1a", id: "014", name: "Volcarona", rarity: "◊◊◊" },
  { set: "A1a", id: "015", name: "Salandit", rarity: "◊" },
  { set: "A1a", id: "016", name: "Salazzle", rarity: "◊" },
  { set: "A1a", id: "017", name: "Magikarp", rarity: "◊" },
  { set: "A1a", id: "018", name: "Gyarados ex", rarity: "◊◊◊◊" },
  { set: "A1a", id: "019", name: "Vaporeon", rarity: "◊◊◊" },
  { set: "A1a", id: "020", name: "Finneon", rarity: "◊" },
  { set: "A1a", id: "021", name: "Lumineon", rarity: "◊◊" },
  { set: "A1a", id: "022", name: "Chewtle", rarity: "◊" },
  { set: "A1a", id: "023", name: "Drednaw", rarity: "◊◊" },
  { set: "A1a", id: "024", name: "Cramorant", rarity: "◊" },
  { set: "A1a", id: "025", name: "Pikachu", rarity: "◊" },
  { set: "A1a", id: "026", name: "Raichu", rarity: "◊◊◊" },
  { set: "A1a", id: "027", name: "Electabuzz", rarity: "◊◊" },
  { set: "A1a", id: "028", name: "Joltik", rarity: "◊" },
  { set: "A1a", id: "029", name: "Galvantula", rarity: "◊◊" },
  { set: "A1a", id: "030", name: "Dedenne", rarity: "◊" },
  { set: "A1a", id: "031", name: "Mew", rarity: "◊◊◊" },
  { set: "A1a", id: "032", name: "Mew ex", rarity: "◊◊◊◊" },
  { set: "A1a", id: "033", name: "Sigilyph", rarity: "◊◊" },
  { set: "A1a", id: "034", name: "Elgyem", rarity: "◊" },
  { set: "A1a", id: "035", name: "Beheeyem", rarity: "◊◊" },
  { set: "A1a", id: "036", name: "Flabébé", rarity: "◊" },
  { set: "A1a", id: "037", name: "Floette", rarity: "◊" },
  { set: "A1a", id: "038", name: "Florges", rarity: "◊◊" },
  { set: "A1a", id: "039", name: "Swirlix", rarity: "◊" },
  { set: "A1a", id: "040", name: "Slurpuff", rarity: "◊" },
  { set: "A1a", id: "041", name: "Mankey", rarity: "◊" },
  { set: "A1a", id: "042", name: "Primeape", rarity: "◊" },
  { set: "A1a", id: "043", name: "Geodude", rarity: "◊" },
  { set: "A1a", id: "044", name: "Graveler", rarity: "◊◊" },
  { set: "A1a", id: "045", name: "Golem", rarity: "◊◊◊" },
  { set: "A1a", id: "046", name: "Aerodactyl ex", rarity: "◊◊◊◊" },
  { set: "A1a", id: "047", name: "Marshadow", rarity: "◊◊◊" },
  { set: "A1a", id: "048", name: "Stonjourner", rarity: "◊◊" },
  { set: "A1a", id: "049", name: "Koffing", rarity: "◊" },
  { set: "A1a", id: "050", name: "Weezing", rarity: "◊◊" },
  { set: "A1a", id: "051", name: "Purrloin", rarity: "◊" },
  { set: "A1a", id: "052", name: "Liepard", rarity: "◊" },
  { set: "A1a", id: "053", name: "Venipede", rarity: "◊" },
  { set: "A1a", id: "054", name: "Whirlipede", rarity: "◊" },
  { set: "A1a", id: "055", name: "Scolipede", rarity: "◊◊" },
  { set: "A1a", id: "056", name: "Druddigon", rarity: "◊◊" },
  { set: "A1a", id: "057", name: "Pidgey", rarity: "◊" },
  { set: "A1a", id: "058", name: "Pidgeotto", rarity: "◊" },
  { set: "A1a", id: "059", name: "Pidgeot ex", rarity: "◊◊◊◊" },
  { set: "A1a", id: "060", name: "Tauros", rarity: "◊◊◊" },
  { set: "A1a", id: "061", name: "Eevee", rarity: "◊" },
  { set: "A1a", id: "062", name: "Chatot", rarity: "◊" },
  { set: "A1a", id: "063", name: "Old Amber", rarity: "◊" },
  { set: "A1a", id: "064", name: "Pokémon Flute", rarity: "◊◊" },
  { set: "A1a", id: "065", name: "Mythical Slab", rarity: "◊◊" },
  { set: "A1a", id: "066", name: "Budding Expeditioner", rarity: "◊◊" },
  { set: "A1a", id: "067", name: "Blue", rarity: "◊◊" },
  { set: "A1a", id: "068", name: "Leaf", rarity: "◊◊" },
  { set: "A1a", id: "069", name: "Exeggutor", rarity: "☆" },
  { set: "A1a", id: "070", name: "Serperior", rarity: "☆" },
  { set: "A1a", id: "071", name: "Salandit", rarity: "☆" },
  { set: "A1a", id: "072", name: "Vaporeon", rarity: "☆" },
  { set: "A1a", id: "073", name: "Dedenne", rarity: "☆" },
  { set: "A1a", id: "074", name: "Marshadow", rarity: "☆" },
  { set: "A1a", id: "075", name: "Celebi ex", rarity: "☆☆" },
  { set: "A1a", id: "076", name: "Gyarados ex", rarity: "☆☆" },
  { set: "A1a", id: "077", name: "Mew ex", rarity: "☆☆" },
  { set: "A1a", id: "078", name: "Aerodactyl ex", rarity: "☆☆" },
  { set: "A1a", id: "079", name: "Pidgeot ex", rarity: "☆☆" },
  { set: "A1a", id: "080", name: "Budding Expeditioner", rarity: "☆☆" },
  { set: "A1a", id: "081", name: "Blue", rarity: "☆☆" },
  { set: "A1a", id: "082", name: "Leaf", rarity: "☆☆" },
  { set: "A1a", id: "083", name: "Mew ex", rarity: "☆☆" },
  { set: "A1a", id: "084", name: "Aerodactyl ex", rarity: "☆☆" },
  { set: "A1a", id: "085", name: "Celebi ex", rarity: "☆☆☆" },
  { set: "A1a", id: "086", name: "Mew ex", rarity: "👑" },
  { set: "A2", id: "001", name: "Oddish", rarity: "◊" },
  { set: "A2", id: "002", name: "Gloom", rarity: "◊" },
  { set: "A2", id: "003", name: "Bellossom", rarity: "◊◊" },
  { set: "A2", id: "004", name: "Tangela", rarity: "◊" },
  { set: "A2", id: "005", name: "Tangrowth", rarity: "◊◊" },
  { set: "A2", id: "006", name: "Yanma", rarity: "◊" },
  { set: "A2", id: "007", name: "Yanmega ex", rarity: "◊◊◊◊" },
  { set: "A2", id: "008", name: "Roselia", rarity: "◊" },
  { set: "A2", id: "009", name: "Roserade", rarity: "◊◊" },
  { set: "A2", id: "010", name: "Turtwig", rarity: "◊" },
  { set: "A2", id: "011", name: "Grotle", rarity: "◊◊" },
  { set: "A2", id: "012", name: "Torterra", rarity: "◊◊◊" },
  { set: "A2", id: "013", name: "Kricketot", rarity: "◊" },
  { set: "A2", id: "014", name: "Kricketune", rarity: "◊" },
  { set: "A2", id: "015", name: "Burmy", rarity: "◊" },
  { set: "A2", id: "016", name: "Wormadam", rarity: "◊" },
  { set: "A2", id: "017", name: "Combee", rarity: "◊" },
  { set: "A2", id: "018", name: "Vespiquen", rarity: "◊◊" },
  { set: "A2", id: "019", name: "Carnivine", rarity: "◊◊" },
  { set: "A2", id: "020", name: "Leafeon", rarity: "◊◊◊" },
  { set: "A2", id: "021", name: "Mow Rotom", rarity: "◊" },
  { set: "A2", id: "022", name: "Shaymin", rarity: "◊◊◊" },
  { set: "A2", id: "023", name: "Magmar", rarity: "◊" },
  { set: "A2", id: "024", name: "Magmortar", rarity: "◊◊◊" },
  { set: "A2", id: "025", name: "Slugma", rarity: "◊" },
  { set: "A2", id: "026", name: "Magcargo", rarity: "◊◊" },
  { set: "A2", id: "027", name: "Chimchar", rarity: "◊" },
  { set: "A2", id: "028", name: "Monferno", rarity: "◊◊" },
  { set: "A2", id: "029", name: "Infernape ex", rarity: "◊◊◊◊" },
  { set: "A2", id: "030", name: "Heat Rotom", rarity: "◊" },
  { set: "A2", id: "031", name: "Swinub", rarity: "◊" },
  { set: "A2", id: "032", name: "Piloswine", rarity: "◊◊" },
  { set: "A2", id: "033", name: "Mamoswine", rarity: "◊◊◊" },
  { set: "A2", id: "034", name: "Regice", rarity: "◊◊" },
  { set: "A2", id: "035", name: "Piplup", rarity: "◊" },
  { set: "A2", id: "036", name: "Prinplup", rarity: "◊◊" },
  { set: "A2", id: "037", name: "Empoleon", rarity: "◊◊◊" },
  { set: "A2", id: "038", name: "Buizel", rarity: "◊" },
  { set: "A2", id: "039", name: "Floatzel", rarity: "◊◊" },
  { set: "A2", id: "040", name: "Shellos", rarity: "◊" },
  { set: "A2", id: "041", name: "Gastrodon", rarity: "◊◊" },
  { set: "A2", id: "042", name: "Finneon", rarity: "◊" },
  { set: "A2", id: "043", name: "Lumineon", rarity: "◊◊" },
  { set: "A2", id: "044", name: "Snover", rarity: "◊" },
  { set: "A2", id: "045", name: "Abomasnow", rarity: "◊◊" },
  { set: "A2", id: "046", name: "Glaceon", rarity: "◊◊◊" },
  { set: "A2", id: "047", name: "Wash Rotom", rarity: "◊" },
  { set: "A2", id: "048", name: "Frost Rotom", rarity: "◊" },
  { set: "A2", id: "049", name: "Palkia ex", rarity: "◊◊◊◊" },
  { set: "A2", id: "050", name: "Manaphy", rarity: "◊◊" },
  { set: "A2", id: "051", name: "Magnemite", rarity: "◊" },
  { set: "A2", id: "052", name: "Magneton", rarity: "◊◊" },
  { set: "A2", id: "053", name: "Magnezone", rarity: "◊◊◊" },
  { set: "A2", id: "054", name: "Voltorb", rarity: "◊" },
  { set: "A2", id: "055", name: "Electrode", rarity: "◊◊" },
  { set: "A2", id: "056", name: "Electabuzz", rarity: "◊" },
  { set: "A2", id: "057", name: "Electivire", rarity: "◊◊◊" },
  { set: "A2", id: "058", name: "Shinx", rarity: "◊" },
  { set: "A2", id: "059", name: "Luxio", rarity: "◊◊" },
  { set: "A2", id: "060", name: "Luxray", rarity: "◊◊◊" },
  { set: "A2", id: "061", name: "Pachirisu ex", rarity: "◊◊◊◊" },
  { set: "A2", id: "062", name: "Rotom", rarity: "◊" },
  { set: "A2", id: "063", name: "Togepi", rarity: "◊" },
  { set: "A2", id: "064", name: "Togetic", rarity: "◊◊" },
  { set: "A2", id: "065", name: "Togekiss", rarity: "◊◊◊" },
  { set: "A2", id: "066", name: "Misdreavus", rarity: "◊" },
  { set: "A2", id: "067", name: "Mismagius ex", rarity: "◊◊◊◊" },
  { set: "A2", id: "068", name: "Ralts", rarity: "◊" },
  { set: "A2", id: "069", name: "Kirlia", rarity: "◊" },
  { set: "A2", id: "070", name: "Duskull", rarity: "◊" },
  { set: "A2", id: "071", name: "Dusclops", rarity: "◊◊" },
  { set: "A2", id: "072", name: "Dusknoir", rarity: "◊◊◊" },
  { set: "A2", id: "073", name: "Drifloon", rarity: "◊" },
  { set: "A2", id: "074", name: "Drifblim", rarity: "◊◊" },
  { set: "A2", id: "075", name: "Uxie", rarity: "◊◊" },
  { set: "A2", id: "076", name: "Mesprit", rarity: "◊◊◊" },
  { set: "A2", id: "077", name: "Azelf", rarity: "◊◊" },
  { set: "A2", id: "078", name: "Giratina", rarity: "◊◊◊" },
  { set: "A2", id: "079", name: "Cresselia", rarity: "◊◊◊" },
  { set: "A2", id: "080", name: "Rhyhorn", rarity: "◊" },
  { set: "A2", id: "081", name: "Rhydon", rarity: "◊◊" },
  { set: "A2", id: "082", name: "Rhyperior", rarity: "◊◊◊" },
  { set: "A2", id: "083", name: "Gligar", rarity: "◊" },
  { set: "A2", id: "084", name: "Gliscor", rarity: "◊◊" },
  { set: "A2", id: "085", name: "Hitmontop", rarity: "◊" },
  { set: "A2", id: "086", name: "Nosepass", rarity: "◊" },
  { set: "A2", id: "087", name: "Regirock", rarity: "◊◊" },
  { set: "A2", id: "088", name: "Cranidos", rarity: "◊◊" },
  { set: "A2", id: "089", name: "Rampardos", rarity: "◊◊◊" },
  { set: "A2", id: "090", name: "Wormadam", rarity: "◊" },
  { set: "A2", id: "091", name: "Riolu", rarity: "◊" },
  { set: "A2", id: "092", name: "Lucario", rarity: "◊◊◊" },
  { set: "A2", id: "093", name: "Hippopotas", rarity: "◊" },
  { set: "A2", id: "094", name: "Hippowdon", rarity: "◊◊" },
  { set: "A2", id: "095", name: "Gallade ex", rarity: "◊◊◊◊" },
  { set: "A2", id: "096", name: "Murkrow", rarity: "◊" },
  { set: "A2", id: "097", name: "Honchkrow", rarity: "◊◊" },
  { set: "A2", id: "098", name: "Sneasel", rarity: "◊" },
  { set: "A2", id: "099", name: "Weavile ex", rarity: "◊◊◊◊" },
  { set: "A2", id: "100", name: "Poochyena", rarity: "◊" },
  { set: "A2", id: "101", name: "Mightyena", rarity: "◊◊" },
  { set: "A2", id: "102", name: "Stunky", rarity: "◊" },
  { set: "A2", id: "103", name: "Skuntank", rarity: "◊◊" },
  { set: "A2", id: "104", name: "Spiritomb", rarity: "◊◊" },
  { set: "A2", id: "105", name: "Skorupi", rarity: "◊" },
  { set: "A2", id: "106", name: "Drapion", rarity: "◊◊" },
  { set: "A2", id: "107", name: "Croagunk", rarity: "◊" },
  { set: "A2", id: "108", name: "Toxicroak", rarity: "◊◊" },
  { set: "A2", id: "109", name: "Darkrai", rarity: "◊◊◊" },
  { set: "A2", id: "110", name: "Darkrai ex", rarity: "◊◊◊◊" },
  { set: "A2", id: "111", name: "Skarmory", rarity: "◊◊" },
  { set: "A2", id: "112", name: "Registeel", rarity: "◊◊" },
  { set: "A2", id: "113", name: "Shieldon", rarity: "◊◊" },
  { set: "A2", id: "114", name: "Bastiodon", rarity: "◊◊◊" },
  { set: "A2", id: "115", name: "Wormadam", rarity: "◊" },
  { set: "A2", id: "116", name: "Bronzor", rarity: "◊" },
  { set: "A2", id: "117", name: "Bronzong", rarity: "◊◊" },
  { set: "A2", id: "118", name: "Probopass", rarity: "◊◊" },
  { set: "A2", id: "119", name: "Dialga ex", rarity: "◊◊◊◊" },
  { set: "A2", id: "120", name: "Heatran", rarity: "◊◊◊" },
  { set: "A2", id: "121", name: "Gible", rarity: "◊" },
  { set: "A2", id: "122", name: "Gabite", rarity: "◊◊" },
  { set: "A2", id: "123", name: "Garchomp", rarity: "◊◊◊" },
  { set: "A2", id: "124", name: "Lickitung", rarity: "◊" },
  { set: "A2", id: "125", name: "Lickilicky ex", rarity: "◊◊◊◊" },
  { set: "A2", id: "126", name: "Eevee", rarity: "◊" },
  { set: "A2", id: "127", name: "Porygon", rarity: "◊" },
  { set: "A2", id: "128", name: "Porygon2", rarity: "◊◊" },
  { set: "A2", id: "129", name: "Porygon-Z", rarity: "◊◊◊" },
  { set: "A2", id: "130", name: "Aipom", rarity: "◊" },
  { set: "A2", id: "131", name: "Ambipom", rarity: "◊" },
  { set: "A2", id: "132", name: "Starly", rarity: "◊" },
  { set: "A2", id: "133", name: "Staravia", rarity: "◊" },
  { set: "A2", id: "134", name: "Staraptor", rarity: "◊◊" },
  { set: "A2", id: "135", name: "Bidoof", rarity: "◊" },
  { set: "A2", id: "136", name: "Bibarel", rarity: "◊" },
  { set: "A2", id: "137", name: "Buneary", rarity: "◊" },
  { set: "A2", id: "138", name: "Lopunny", rarity: "◊" },
  { set: "A2", id: "139", name: "Glameow", rarity: "◊" },
  { set: "A2", id: "140", name: "Purugly", rarity: "◊◊" },
  { set: "A2", id: "141", name: "Chatot", rarity: "◊" },
  { set: "A2", id: "142", name: "Fan Rotom", rarity: "◊" },
  { set: "A2", id: "143", name: "Regigigas", rarity: "◊◊◊" },
  { set: "A2", id: "144", name: "Skull Fossil", rarity: "◊" },
  { set: "A2", id: "145", name: "Armor Fossil", rarity: "◊" },
  { set: "A2", id: "146", name: "Pokémon Communication", rarity: "◊◊" },
  { set: "A2", id: "147", name: "Giant Cape", rarity: "◊◊" },
  { set: "A2", id: "148", name: "Rocky Helmet", rarity: "◊◊" },
  { set: "A2", id: "149", name: "Lum Berry", rarity: "◊◊" },
  { set: "A2", id: "150", name: "Cyrus", rarity: "◊◊" },
  { set: "A2", id: "151", name: "Team Galactic Grunt", rarity: "◊◊" },
  { set: "A2", id: "152", name: "Cynthia", rarity: "◊◊" },
  { set: "A2", id: "153", name: "Volkner", rarity: "◊◊" },
  { set: "A2", id: "154", name: "Dawn", rarity: "◊◊" },
  { set: "A2", id: "155", name: "Mars", rarity: "◊◊" },
  { set: "A2", id: "156", name: "Tangrowth", rarity: "☆" },
  { set: "A2", id: "157", name: "Combee", rarity: "☆" },
  { set: "A2", id: "158", name: "Carnivine", rarity: "☆" },
  { set: "A2", id: "159", name: "Shaymin", rarity: "☆" },
  { set: "A2", id: "160", name: "Mamoswine", rarity: "☆" },
  { set: "A2", id: "161", name: "Gastrodon", rarity: "☆" },
  { set: "A2", id: "162", name: "Manaphy", rarity: "☆" },
  { set: "A2", id: "163", name: "Shinx", rarity: "☆" },
  { set: "A2", id: "164", name: "Rotom", rarity: "☆" },
  { set: "A2", id: "165", name: "Drifloon", rarity: "☆" },
  { set: "A2", id: "166", name: "Mesprit", rarity: "☆" },
  { set: "A2", id: "167", name: "Giratina", rarity: "☆" },
  { set: "A2", id: "168", name: "Cresselia", rarity: "☆" },
  { set: "A2", id: "169", name: "Rhyperior", rarity: "☆" },
  { set: "A2", id: "170", name: "Lucario", rarity: "☆" },
  { set: "A2", id: "171", name: "Hippopotas", rarity: "☆" },
  { set: "A2", id: "172", name: "Spiritomb", rarity: "☆" },
  { set: "A2", id: "173", name: "Croagunk", rarity: "☆" },
  { set: "A2", id: "174", name: "Heatran", rarity: "☆" },
  { set: "A2", id: "175", name: "Garchomp", rarity: "☆" },
  { set: "A2", id: "176", name: "Staraptor", rarity: "☆" },
  { set: "A2", id: "177", name: "Bidoof", rarity: "☆" },
  { set: "A2", id: "178", name: "Glameow", rarity: "☆" },
  { set: "A2", id: "179", name: "Regigigas", rarity: "☆" },
  { set: "A2", id: "180", name: "Yanmega ex", rarity: "☆☆" },
  { set: "A2", id: "181", name: "Infernape ex", rarity: "☆☆" },
  { set: "A2", id: "182", name: "Palkia ex", rarity: "☆☆" },
  { set: "A2", id: "183", name: "Pachirisu ex", rarity: "☆☆" },
  { set: "A2", id: "184", name: "Mismagius ex", rarity: "☆☆" },
  { set: "A2", id: "185", name: "Gallade ex", rarity: "☆☆" },
  { set: "A2", id: "186", name: "Weavile ex", rarity: "☆☆" },
  { set: "A2", id: "187", name: "Darkrai ex", rarity: "☆☆" },
  { set: "A2", id: "188", name: "Dialga ex", rarity: "☆☆" },
  { set: "A2", id: "189", name: "Lickilicky ex", rarity: "☆☆" },
  { set: "A2", id: "190", name: "Cyrus", rarity: "☆☆" },
  { set: "A2", id: "191", name: "Team Galactic Grunt", rarity: "☆☆" },
  { set: "A2", id: "192", name: "Cynthia", rarity: "☆☆" },
  { set: "A2", id: "193", name: "Volkner", rarity: "☆☆" },
  { set: "A2", id: "194", name: "Dawn", rarity: "☆☆" },
  { set: "A2", id: "195", name: "Mars", rarity: "☆☆" },
  { set: "A2", id: "196", name: "Yanmega ex", rarity: "☆☆" },
  { set: "A2", id: "197", name: "Infernape ex", rarity: "☆☆" },
  { set: "A2", id: "198", name: "Pachirisu ex", rarity: "☆☆" },
  { set: "A2", id: "199", name: "Mismagius ex", rarity: "☆☆" },
  { set: "A2", id: "200", name: "Gallade ex", rarity: "☆☆" },
  { set: "A2", id: "201", name: "Weavile ex", rarity: "☆☆" },
  { set: "A2", id: "202", name: "Darkrai ex", rarity: "☆☆" },
  { set: "A2", id: "203", name: "Lickilicky ex", rarity: "☆☆" },
  { set: "A2", id: "204", name: "Palkia ex", rarity: "☆☆☆" },
  { set: "A2", id: "205", name: "Dialga ex", rarity: "☆☆☆" },
  { set: "A2", id: "206", name: "Palkia ex", rarity: "👑" },
  { set: "A2", id: "207", name: "Dialga ex", rarity: "👑" },
  { set: "A2a", id: "001", name: "Heracross", rarity: "◊◊" },
  { set: "A2a", id: "002", name: "Burmy", rarity: "◊" },
  { set: "A2a", id: "003", name: "Mothim", rarity: "◊◊" },
  { set: "A2a", id: "004", name: "Combee", rarity: "◊" },
  { set: "A2a", id: "005", name: "Vespiquen", rarity: "◊◊" },
  { set: "A2a", id: "006", name: "Cherubi", rarity: "◊" },
  { set: "A2a", id: "007", name: "Cherrim", rarity: "◊◊" },
  { set: "A2a", id: "008", name: "Cherrim", rarity: "◊◊" },
  { set: "A2a", id: "009", name: "Carnivine", rarity: "◊◊◊" },
  { set: "A2a", id: "010", name: "Leafeon ex", rarity: "◊◊◊◊" },
  { set: "A2a", id: "011", name: "Houndour", rarity: "◊" },
  { set: "A2a", id: "012", name: "Houndoom", rarity: "◊◊" },
  { set: "A2a", id: "013", name: "Heatran", rarity: "◊◊◊" },
  { set: "A2a", id: "014", name: "Marill", rarity: "◊" },
  { set: "A2a", id: "015", name: "Azumarill", rarity: "◊" },
  { set: "A2a", id: "016", name: "Barboach", rarity: "◊" },
  { set: "A2a", id: "017", name: "Whiscash", rarity: "◊◊" },
  { set: "A2a", id: "018", name: "Snorunt", rarity: "◊" },
  { set: "A2a", id: "019", name: "Froslass", rarity: "◊◊" },
  { set: "A2a", id: "020", name: "Snover", rarity: "◊" },
  { set: "A2a", id: "021", name: "Abomasnow", rarity: "◊◊◊" },
  { set: "A2a", id: "022", name: "Glaceon ex", rarity: "◊◊◊◊" },
  { set: "A2a", id: "023", name: "Origin Forme Palkia", rarity: "◊◊◊" },
  { set: "A2a", id: "024", name: "Phione", rarity: "◊◊" },
  { set: "A2a", id: "025", name: "Pikachu", rarity: "◊" },
  { set: "A2a", id: "026", name: "Raichu", rarity: "◊◊◊" },
  { set: "A2a", id: "027", name: "Electrike", rarity: "◊" },
  { set: "A2a", id: "028", name: "Manectric", rarity: "◊◊" },
  { set: "A2a", id: "029", name: "Clefairy", rarity: "◊" },
  { set: "A2a", id: "030", name: "Clefable", rarity: "◊◊" },
  { set: "A2a", id: "031", name: "Gastly", rarity: "◊" },
  { set: "A2a", id: "032", name: "Haunter", rarity: "◊" },
  { set: "A2a", id: "033", name: "Gengar", rarity: "◊◊" },
  { set: "A2a", id: "034", name: "Unown", rarity: "◊◊" },
  { set: "A2a", id: "035", name: "Rotom", rarity: "◊◊◊" },
  { set: "A2a", id: "036", name: "Sudowoodo", rarity: "◊◊" },
  { set: "A2a", id: "037", name: "Phanpy", rarity: "◊" },
  { set: "A2a", id: "038", name: "Donphan", rarity: "◊◊" },
  { set: "A2a", id: "039", name: "Larvitar", rarity: "◊" },
  { set: "A2a", id: "040", name: "Pupitar", rarity: "◊◊" },
  { set: "A2a", id: "041", name: "Tyranitar", rarity: "◊◊◊" },
  { set: "A2a", id: "042", name: "Nosepass", rarity: "◊" },
  { set: "A2a", id: "043", name: "Meditite", rarity: "◊" },
  { set: "A2a", id: "044", name: "Medicham", rarity: "◊◊" },
  { set: "A2a", id: "045", name: "Gible", rarity: "◊" },
  { set: "A2a", id: "046", name: "Gabite", rarity: "◊" },
  { set: "A2a", id: "047", name: "Garchomp ex", rarity: "◊◊◊◊" },
  { set: "A2a", id: "048", name: "Zubat", rarity: "◊" },
  { set: "A2a", id: "049", name: "Golbat", rarity: "◊" },
  { set: "A2a", id: "050", name: "Crobat", rarity: "◊◊◊" },
  { set: "A2a", id: "051", name: "Croagunk", rarity: "◊" },
  { set: "A2a", id: "052", name: "Toxicroak", rarity: "◊◊" },
  { set: "A2a", id: "053", name: "Magnemite", rarity: "◊" },
  { set: "A2a", id: "054", name: "Magneton", rarity: "◊" },
  { set: "A2a", id: "055", name: "Magnezone", rarity: "◊◊◊" },
  { set: "A2a", id: "056", name: "Mawile", rarity: "◊" },
  { set: "A2a", id: "057", name: "Probopass ex", rarity: "◊◊◊◊" },
  { set: "A2a", id: "058", name: "Bronzor", rarity: "◊" },
  { set: "A2a", id: "059", name: "Bronzong", rarity: "◊◊" },
  { set: "A2a", id: "060", name: "Origin Forme Dialga", rarity: "◊◊◊" },
  { set: "A2a", id: "061", name: "Giratina", rarity: "◊◊◊" },
  { set: "A2a", id: "062", name: "Eevee", rarity: "◊" },
  { set: "A2a", id: "063", name: "Snorlax", rarity: "◊◊" },
  { set: "A2a", id: "064", name: "Hoothoot", rarity: "◊" },
  { set: "A2a", id: "065", name: "Noctowl", rarity: "◊◊" },
  { set: "A2a", id: "066", name: "Starly", rarity: "◊" },
  { set: "A2a", id: "067", name: "Staravia", rarity: "◊" },
  { set: "A2a", id: "068", name: "Staraptor", rarity: "◊◊" },
  { set: "A2a", id: "069", name: "Shaymin", rarity: "◊◊◊" },
  { set: "A2a", id: "070", name: "Arceus", rarity: "◊◊◊" },
  { set: "A2a", id: "071", name: "Arceus ex", rarity: "◊◊◊◊" },
  { set: "A2a", id: "072", name: "Irida", rarity: "◊◊" },
  { set: "A2a", id: "073", name: "Celestic Town Elder", rarity: "◊◊" },
  { set: "A2a", id: "074", name: "Barry", rarity: "◊◊" },
  { set: "A2a", id: "075", name: "Adaman", rarity: "◊◊" },
  { set: "A2a", id: "076", name: "Houndoom", rarity: "☆" },
  { set: "A2a", id: "077", name: "Marill", rarity: "☆" },
  { set: "A2a", id: "078", name: "Unown", rarity: "☆" },
  { set: "A2a", id: "079", name: "Sudowoodo", rarity: "☆" },
  { set: "A2a", id: "080", name: "Magnemite", rarity: "☆" },
  { set: "A2a", id: "081", name: "Shaymin", rarity: "☆" },
  { set: "A2a", id: "082", name: "Leafeon ex", rarity: "☆☆" },
  { set: "A2a", id: "083", name: "Glaceon ex", rarity: "☆☆" },
  { set: "A2a", id: "084", name: "Garchomp ex", rarity: "☆☆" },
  { set: "A2a", id: "085", name: "Probopass ex", rarity: "☆☆" },
  { set: "A2a", id: "086", name: "Arceus ex", rarity: "☆☆" },
  { set: "A2a", id: "087", name: "Irida", rarity: "☆☆" },
  { set: "A2a", id: "088", name: "Celestic Town Elder", rarity: "☆☆" },
  { set: "A2a", id: "089", name: "Barry", rarity: "☆☆" },
  { set: "A2a", id: "090", name: "Adaman", rarity: "☆☆" },
  { set: "A2a", id: "091", name: "Leafeon ex", rarity: "☆☆" },
  { set: "A2a", id: "092", name: "Glaceon ex", rarity: "☆☆" },
  { set: "A2a", id: "093", name: "Garchomp ex", rarity: "☆☆" },
  { set: "A2a", id: "094", name: "Probopass ex", rarity: "☆☆" },
  { set: "A2a", id: "095", name: "Arceus ex", rarity: "☆☆☆" },
  { set: "A2a", id: "096", name: "Arceus ex", rarity: "👑" },
  { set: "P-A", id: "001", name: "Potion", rarity: "Promo" },
  { set: "P-A", id: "002", name: "X Speed", rarity: "Promo" },
  { set: "P-A", id: "003", name: "Hand Scope", rarity: "Promo" },
  { set: "P-A", id: "004", name: "Pokédex", rarity: "Promo" },
  { set: "P-A", id: "005", name: "Poké Ball", rarity: "Promo" },
  { set: "P-A", id: "006", name: "Red Card", rarity: "Promo" },
  { set: "P-A", id: "007", name: "Professor's Research", rarity: "Promo" },
  { set: "P-A", id: "008", name: "Pokédex", rarity: "Promo" },
  { set: "P-A", id: "009", name: "Pikachu", rarity: "Promo" },
  { set: "P-A", id: "010", name: "Mewtwo", rarity: "Promo" },
  { set: "P-A", id: "011", name: "Chansey", rarity: "Promo" },
  { set: "P-A", id: "012", name: "Meowth", rarity: "Promo" },
  { set: "P-A", id: "013", name: "Butterfree", rarity: "Promo" },
  { set: "P-A", id: "014", name: "Lapras ex", rarity: "Promo" },
  { set: "P-A", id: "015", name: "Pikachu", rarity: "Promo" },
  { set: "P-A", id: "016", name: "Clefairy", rarity: "Promo" },
  { set: "P-A", id: "017", name: "Mankey", rarity: "Promo" },
  { set: "P-A", id: "018", name: "Venusaur", rarity: "Promo" },
  { set: "P-A", id: "019", name: "Greninja", rarity: "Promo" },
  { set: "P-A", id: "020", name: "Haunter", rarity: "Promo" },
  { set: "P-A", id: "021", name: "Onix", rarity: "Promo" },
  { set: "P-A", id: "022", name: "Jigglypuff", rarity: "Promo" },
  { set: "P-A", id: "023", name: "Bulbasaur", rarity: "Promo" },
  { set: "P-A", id: "024", name: "Magnemite", rarity: "Promo" },
  { set: "P-A", id: "025", name: "Moltres ex", rarity: "Promo" },
  { set: "P-A", id: "026", name: "Pikachu", rarity: "Promo" },
  { set: "P-A", id: "027", name: "Snivy", rarity: "Promo" },
  { set: "P-A", id: "028", name: "Volcarona", rarity: "Promo" },
  { set: "P-A", id: "029", name: "Blastoise", rarity: "Promo" },
  { set: "P-A", id: "030", name: "Eevee", rarity: "Promo" },
  { set: "P-A", id: "031", name: "Cinccino", rarity: "Promo" },
  { set: "P-A", id: "032", name: "Charmander", rarity: "Promo" },
  { set: "P-A", id: "033", name: "Squirtle", rarity: "Promo" },
  { set: "P-A", id: "034", name: "Piplup", rarity: "Promo" },
  { set: "P-A", id: "035", name: "Turtwig", rarity: "Promo" },
  { set: "P-A", id: "036", name: "Electivire", rarity: "Promo" },
  { set: "P-A", id: "037", name: "Cresselia ex", rarity: "Promo" },
  { set: "P-A", id: "038", name: "Misdreavus", rarity: "Promo" },
  { set: "P-A", id: "039", name: "Skarmory", rarity: "Promo" },
  { set: "P-A", id: "040", name: "Chimchar", rarity: "Promo" },
  { set: "P-A", id: "041", name: "Togepi", rarity: "Promo" },
  { set: "P-A", id: "042", name: "Darkrai ex", rarity: "Promo" },
  { set: "P-A", id: "043", name: "Cherrim", rarity: "Promo" },
  { set: "P-A", id: "044", name: "Raichu", rarity: "Promo" },
  { set: "P-A", id: "045", name: "Nosepass", rarity: "Promo" },
  { set: "P-A", id: "046", name: "Gible", rarity: "Promo" },
  { set: "P-A", id: "047", name: "Staraptor", rarity: "Promo" },
  { set: "P-A", id: "048", name: "Manaphy", rarity: "Promo" },
  { set: "P-A", id: "049", name: "Snorlax", rarity: "Promo" },
];
